### ISSUE TITLE
yo kevoree does not work on Intel Edison

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#54]
It seems `yo kevoree` is not working on Intel Edison. Maybe the problem comes more from Yeoman than Kevoree:

```
Error: EACCES, permission denied '/home/root/.config'
    at Object.fs.mkdirSync (fs.js:642:18)
    at sync (/usr/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:76:24)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:26:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/cli.js:123:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

After creating a file `/home/root/.config` to help a little bit, I got:

```
Error: ENOTDIR, not a directory '/home/root/.config/configstore/insight-yo.yml'
    at Object.fs.openSync (evalmachine.<anonymous>:427:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:284:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:26:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/cli.js:123:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by brice-morin** [comment]
It seems we have to play with chown/chmod a bit on the Edison to get the JS toolchain to work properly. I do not think it is a problem related to the Kevoree generator, and will close that issue
