### ISSUE TITLE
NullPointerException at org.sintef.thingml.resource.thingml.mopp.ThingmlANTLRParserBase

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/heads_ide#74]
While checking issue #72, I got

Compiling with "Plain Java" (Platform: java)
Selected input file: L/3.1_ThingML_Components_3_Kevoree_Deployments/_java/timer.thingml (C:\Users\mask\git\skorsky\training\3.Wrapping_ThingML_into_Kevoree\3.1_ThingML_Components_3_Kevoree_Deployments\_java\timer.thingml)
ERROR: Exeption calling ThingML Compiler: nullPlease contact the ThingML development teamjava.lang.NullPointerException
	at org.sintef.thingml.resource.thingml.mopp.ThingmlANTLRParserBase.registerContextDependentProxy(ThingmlANTLRParserBase.java:159)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_ReceiveMessage(ThingmlParser.java:12027)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_Event(ThingmlParser.java:28582)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_InternalTransition(ThingmlParser.java:11579)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_State(ThingmlParser.java:8736)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_StateMachine(ThingmlParser.java:7841)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_Thing(ThingmlParser.java:3299)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_Type(ThingmlParser.java:28067)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse_org_sintef_thingml_ThingMLModel(ThingmlParser.java:1021)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.start(ThingmlParser.java:814)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.doParse(ThingmlParser.java:362)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlParser.parse(ThingmlParser.java:562)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlResource.doLoad(ThingmlResource.java:204)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlResource.load(ThingmlResource.java:578)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.thingml.eclipse.ui.commands.CompileThingFile.execute(CompileThingFile.java:108)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:830)
	at org.eclipse.ui.menus.CommandContributionItem.access$21(CommandContributionItem.java:816)
	at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:806)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

I used ThingML feature
  ThingML	0.6.0.201510140911	org.thingml.eclipse.feature.feature.group

Is something wrong with the AntLR configuration?

**Comment by brice-morin** [comment]
Yes, it is very related to #72
