### ISSUE TITLE
Kevoree error

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#79]
11:44:58 INFO WSGroup "sync" connected to master server ws://10.10.0.1:9000
This suddenly happened today when I was about to start up:
(Was ok yesterday)

````
/home/heads/demo/node_modules/kevoree-comp-mqttpubclient/node_modules/kevoree-entities/node_modules/kevoree-library/kevoree-library.js:17455
});
^
SyntaxError: Unexpected token )
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/heads/demo/node_modules/kevoree-comp-mqttpubclient/                      node_modules/kevoree-entities/lib/Dictionary.js:2:23)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
````

**Comment by kehusa** [comment]
deleting node_modules and trying again fixed it
