### ISSUE TITLE
Error when generating code

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#86]
After updating to last version of the ThingML code generator, I got this exception when trying to generate the code to day:
Compiling with "Javascript for NodeJS" (Platform: nodejs)
Selected input file: L/Training/3.Wrapping_ThingML_into_Kevoree/3.3_Contrib/Tellu/Home-gw/_javascript/ServerJS.thingml (C:\Users\KnutEilif\Heads_13.02\workspace\Training\3.Wrapping_ThingML_into_Kevoree\3.3_Contrib\Tellu\Home-gw\_javascript\ServerJS.thingml)
ERROR: Exeption calling ThingML Compiler: org.sintef.thingml.Configuration.isFragment()ZPlease contact the ThingML development teamjava.lang.NoSuchMethodError: org.sintef.thingml.Configuration.isFragment()Z
	at org.thingml.eclipse.ui.commands.CompileThingFile.execute(CompileThingFile.java:134)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:829)
	at org.eclipse.ui.menus.CommandContributionItem.access$21(CommandContributionItem.java:815)
	at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:805)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

Please help!!

**Comment by Lyadis** [comment]
Do you use the `group` keyword in your ThingML configuration somewhere?

**Comment by kehusa** [comment]
No,

This is the current config:
```
configuration HomeGW  
@kevscript "/Training/3.Wrapping_ThingML_into_Kevoree/3.3_Contrib/Tellu/Home-gw/kevs/dynHomeGW.kevs"
{
    instance server : FallServer   
}
```

**Comment by kehusa** [comment]
To test, just try to run the nodejs/kevoree generator on Training\3.Wrapping_ThingML_into_Kevoree\3.3_Contrib\Tellu\Home-gw\_javascript\ServerJS.thingml

**Comment by Lyadis** [comment]
I'm not sure I can fix this easily without @brice-morin , but may I suggest you to roolback your version of ThingML temporarly (If you didn't do any customization on it.) with
```
git reset --hard <commit id>
```
I'm suspecting [this commit](https://github.com/SINTEF-9012/ThingML/commit/711aa7e9af7d9df901cc347874fa8f21152bd91b) to be the cause of your problems, so I suggest you rollback to [this one](https://github.com/SINTEF-9012/ThingML/commit/5d76737cac757eefbb2fa4724053e853ccb71d25) by using `git reset --hard 5d76737cac757eefbb2fa4724053e853ccb71d25`

**Comment by brice-morin** [comment]
It is related to the suppression of group (hence isFragment does not exists anymore). Either I forgot to regenerate plugins or it is still one call to that method somewhere.Anyway, it is easy to fix (simply remove any call to isFragment and any code that depends on it)

**Comment by Lyadis** [comment]
Ok, I've found the line. Does it fixe your problem @kehusa ?

**Comment by brice-morin** [comment]
note that you need to wait some 10-15 minutes before new version is available on the update site

**Comment by brice-morin** [comment]
Note also that some small but useful missing features have been introduced like `>=`, `<=`, `++` and `--`, which can simplify (a bit) some logic.

**Comment by kehusa** [comment]
Thanks a lot. Have to regenerate all components after the Kevoree registry
restart today.

Regards Knut Eilif

fre. 15. jan. 2016, 17:56 skrev Brice Morin <notifications@github.com>:

**Comment by barais** [comment]
I can add them to the continueous integration to avoid such issue

**Comment by kehusa** [comment]
Checked out and is now working. Thanks.


Knut Eilif

fre. 15. jan. 2016, 17:58 skrev Knut Eilif Husa <knut.eilif.husa@tellu.no>:
