### ISSUE TITLE
kevlib.json for MQTTSubClient 2.0.2

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#89]
I get this when trying to upgrade to MQTTSubClient 2.0.2 on the RPI:

Error: Cannot find module '/home/pi/test/node_modules/kevoree-comp-mqttsubclient/kevlib.json'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at ..

Using grunt on my pc the component worked ok
Help is wanted

**Comment by maxleiko** [comment]
You get that when doing what ?
