### ISSUE TITLE
Cycling of removal and adding nodes when using onConnect/onDisconnect statement

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#91]
After the last update of the Javascript node I have experienced that the system may get in a state where nodes are continuously connecting and disconnecting if more than one node is added to the system. One node gets connected, another is disconnected, it reconnects, the first one is then connected again and so on. It may eventually get to a stable state. 
I don't think I saw this behavior previously to the last update of the Javascript node.

**Comment by kehusa** [comment]
Here you see the cycling behaviour between nodes FN1 and FN3:
```
06:13:15 INFO WSGroup Applying model locally...
06:13:17 ALL KevoreeLogger Set logLevel= debug
06:13:17 DEBUG UpdateDictiona. sync.onDisconnect =
06:13:17 DEBUG UpdateDictiona. sync.onConnect =
06:13:17 DEBUG UpdateInstance node0
06:13:17 INFO WSGroup "sync" listen on 9000
06:13:17 DEBUG UpdateInstance sync
06:13:17 INFO KevoreeCore Model deployed successfully: 5 adaptations (2312ms)
06:13:18 INFO WSGroup New client registered "FN1"
06:13:21 DEBUG WSGroup Client's "FN1" model has been merged with the current one
06:13:21 DEBUG WSGroup onConnect KevScript to process:

06:13:23 INFO WSGroup Broadcasting current model to 1 client
06:13:23 DEBUG KevoreeCore Deploy process started...
06:13:25 DEBUG UpdateDictiona. node0.logLevel = INFO
06:13:25 ALL KevoreeLogger Set logLevel= info
06:13:25 INFO KevoreeCore Model deployed successfully: 2 adaptations (2435ms)
06:13:25 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:18                                                               83
06:13:25 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:18                                                               83
06:13:27 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:13:27 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
06:13:27 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker

06:13:32 INFO WSGroup Broadcasting current model to 1 client
06:13:34 INFO KevoreeCore Model deployed successfully: 0 adaptations (2427ms)
06:13:34 INFO WSGroup New client registered "FN1"

06:13:40 INFO WSGroup Broadcasting current model to 1 client
06:13:44 INFO KevoreeCore Model deployed successfully: 0 adaptations (3633ms)
06:13:44 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:18                                                               83
06:13:44 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:18                                                               83
06:13:44 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
06:13:44 INFO MQTTSubClient comp846 closed connection with localhost:1883
06:13:44 INFO WSGroup New client registered "FN3"

06:13:51 INFO WSGroup Broadcasting current model to 2 clients
06:13:55 INFO KevoreeCore Model deployed successfully: 0 adaptations (4494ms)
06:13:55 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
06:13:55 INFO MQTTSubClient comp846 connected to localhost:1883
06:13:55 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
06:13:55 INFO MQTTSubClient comp846 subscribed to topic sensor/button
06:13:55 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:13:55 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
06:13:55 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker

06:13:58 INFO WSGroup Broadcasting current model to 1 client
06:14:01 INFO KevoreeCore Model deployed successfully: 0 adaptations (2529ms)
06:14:01 INFO WSGroup New client registered "FN1"

06:14:06 INFO WSGroup Broadcasting current model to 2 clients
06:14:08 INFO KevoreeCore Model deployed successfully: 0 adaptations (2174ms)

06:14:11 INFO WSGroup Broadcasting current model to 1 client
06:14:13 INFO KevoreeCore Model deployed successfully: 0 adaptations (2178ms)
06:14:14 INFO WSGroup New client registered "FN3"

06:14:19 INFO WSGroup Broadcasting current model to 2 clients
06:14:21 INFO KevoreeCore Model deployed successfully: 0 adaptations (2253ms)

06:14:24 INFO WSGroup Broadcasting current model to 1 client
06:14:27 INFO KevoreeCore Model deployed successfully: 0 adaptations (2308ms)
06:14:27 INFO WSGroup New client registered "FN1"
```
06:14:32 INFO WSGroup Broadcasting current model to 2 clients
06:14:34 INFO KevoreeCore Model deployed successfully: 0 adaptations (2131ms)

06:14:37 INFO WSGroup Broadcasting current model to 1 client
06:14:40 INFO KevoreeCore Model deployed successfully: 0 adaptations (2256ms)
06:14:40 INFO WSGroup New client registered "FN3"

06:14:45 INFO WSGroup Broadcasting current model to 2 clients
```

**Comment by kehusa** [comment]
One more log. The cycling behaviour started like this:

Starting from a fresh system, bringing one node up at a time everything was stable.
Removing node FN4, and the adding node FN4 again got the cycling started.

```
HomeGWLightController_lightSwitch (LightSwitchServer): smarttracker!postJson({"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]})
HomeGWLightController_lightSwitch (LightSwitch): ZWave?valueChanged(3, 50, [object Object])
HomeGWLightController_lightSwitch (LightSwitch): internal event ZWave?valueChanged
Value changed: 3,50,0.0HomeGWLightController_lightSwitch (LightSwitch): Start createObservation(off)...
06:29:47 INFO MQTTPubClient "pubmqtt" publishing "{"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]}" to "test/smarttracker/pressure"
HomeGWLightController_lightSwitch (LightSwitchServer): smarttracker!postJson({"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]})
HomeGWLightController_lightSwitch (LightSwitch): ZWave?nodeReady(3, [object Object])
HomeGWLightController_lightSwitch (LightSwitch): internal event ZWave?nodeReady
Node ready: 3:[object Object]HomeGWLightController_lightSwitch (LightSwitch): ZWave?scanComplete()
06:29:47 INFO MQTTPubClient "pubmqtt" publishing "{"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]}" to "test/smarttracker/pressure"
06:30:10 INFO WSGroup Pull requested
06:30:44 INFO WSGroup New client registered "FN3"

add FN3.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN3.FieldNode_0.Properties_nodeName__var = "FN3"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN3.submqtt : MQTTSubClient/2.0.1
set FN3.submqtt.topic = "meg/smarttracker"
set FN3.submqtt.host = "10.10.0.1"
set FN3.submqtt.port = "1883"

add FN3.pubmqtt : MQTTPubClient/2.0.1
set FN3.pubmqtt.topic = "test/smarttracker"
set FN3.pubmqtt.host = "10.10.0.1"
set FN3.pubmqtt.port = "1883"

add pubchan-FN3 : LocalChannel
add subchan-FN3 : LocalChannel

bind FN3.FieldNode_0.sen_sen_readingJson_out pubchan-FN3

bind FN3.pubmqtt.jsonPub pubchan-FN3
bind FN3.submqtt.onTopicAndMsg subchan-FN3

//bind FN3.FieldNode_0.Fie_sen_reading_out chan
//bind FN3.FieldNode_0.Fie_sen_ready_out chan
//bind FN3.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN3.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN3.FieldNode_0.Fie_sen_read_in chan1


06:30:49 INFO WSGroup Broadcasting current model to 2 clients
06:30:51 INFO KevoreeCore Model deployed successfully: 0 adaptations (2092ms)
06:32:08 INFO WSGroup New client registered "FN1"

add FN1.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN1.FieldNode_0.Properties_nodeName__var = "FN1"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN1.submqtt : MQTTSubClient/2.0.1
set FN1.submqtt.topic = "meg/smarttracker"
set FN1.submqtt.host = "10.10.0.1"
set FN1.submqtt.port = "1883"

add FN1.pubmqtt : MQTTPubClient/2.0.1
set FN1.pubmqtt.topic = "test/smarttracker"
set FN1.pubmqtt.host = "10.10.0.1"
set FN1.pubmqtt.port = "1883"

add pubchan-FN1 : LocalChannel
add subchan-FN1 : LocalChannel

bind FN1.FieldNode_0.sen_sen_readingJson_out pubchan-FN1

bind FN1.pubmqtt.jsonPub pubchan-FN1
bind FN1.submqtt.onTopicAndMsg subchan-FN1

//bind FN1.FieldNode_0.Fie_sen_reading_out chan
//bind FN1.FieldNode_0.Fie_sen_ready_out chan
//bind FN1.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN1.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN1.FieldNode_0.Fie_sen_read_in chan1


06:32:11 INFO WSGroup Broadcasting current model to 3 clients
06:32:13 INFO KevoreeCore Model deployed successfully: 0 adaptations (2142ms)
06:33:38 INFO WSGroup New client registered "FN4"

add FN4.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN4.FieldNode_0.Properties_nodeName__var = "FN4"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN4.submqtt : MQTTSubClient/2.0.1
set FN4.submqtt.topic = "meg/smarttracker"
set FN4.submqtt.host = "10.10.0.1"
set FN4.submqtt.port = "1883"

add FN4.pubmqtt : MQTTPubClient/2.0.1
set FN4.pubmqtt.topic = "test/smarttracker"
set FN4.pubmqtt.host = "10.10.0.1"
set FN4.pubmqtt.port = "1883"

add pubchan-FN4 : LocalChannel
add subchan-FN4 : LocalChannel

bind FN4.FieldNode_0.sen_sen_readingJson_out pubchan-FN4

bind FN4.pubmqtt.jsonPub pubchan-FN4
bind FN4.submqtt.onTopicAndMsg subchan-FN4

//bind FN4.FieldNode_0.Fie_sen_reading_out chan
//bind FN4.FieldNode_0.Fie_sen_ready_out chan
//bind FN4.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN4.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN4.FieldNode_0.Fie_sen_read_in chan1


06:33:43 INFO WSGroup Broadcasting current model to 4 clients
06:33:46 INFO KevoreeCore Model deployed successfully: 0 adaptations (3105ms)

remove FN4

06:34:50 INFO WSGroup Broadcasting current model to 3 clients
06:34:53 INFO KevoreeCore Model deployed successfully: 0 adaptations (2336ms)
06:34:53 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
06:34:54 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:35:54 INFO WSGroup New client registered "FN4"

add FN4.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN4.FieldNode_0.Properties_nodeName__var = "FN4"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN4.submqtt : MQTTSubClient/2.0.1
set FN4.submqtt.topic = "meg/smarttracker"
set FN4.submqtt.host = "10.10.0.1"
set FN4.submqtt.port = "1883"

add FN4.pubmqtt : MQTTPubClient/2.0.1
set FN4.pubmqtt.topic = "test/smarttracker"
set FN4.pubmqtt.host = "10.10.0.1"
set FN4.pubmqtt.port = "1883"

add pubchan-FN4 : LocalChannel
add subchan-FN4 : LocalChannel

bind FN4.FieldNode_0.sen_sen_readingJson_out pubchan-FN4

bind FN4.pubmqtt.jsonPub pubchan-FN4
bind FN4.submqtt.onTopicAndMsg subchan-FN4

//bind FN4.FieldNode_0.Fie_sen_reading_out chan
//bind FN4.FieldNode_0.Fie_sen_ready_out chan
//bind FN4.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN4.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN4.FieldNode_0.Fie_sen_read_in chan1


06:35:57 INFO WSGroup Broadcasting current model to 4 clients
06:36:00 INFO KevoreeCore Model deployed successfully: 0 adaptations (2462ms)
06:36:00 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
06:36:01 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883

remove FN3

06:36:06 INFO WSGroup Broadcasting current model to 3 clients
06:36:08 INFO KevoreeCore Model deployed successfully: 0 adaptations (2250ms)

remove FN1

06:36:11 INFO WSGroup Broadcasting current model to 3 clients
06:36:13 INFO KevoreeCore Model deployed successfully: 0 adaptations (2129ms)
06:36:13 INFO WSGroup New client registered "FN3"

add FN3.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN3.FieldNode_0.Properties_nodeName__var = "FN3"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN3.submqtt : MQTTSubClient/2.0.1
set FN3.submqtt.topic = "meg/smarttracker"
set FN3.submqtt.host = "10.10.0.1"
set FN3.submqtt.port = "1883"

add FN3.pubmqtt : MQTTPubClient/2.0.1
set FN3.pubmqtt.topic = "test/smarttracker"
set FN3.pubmqtt.host = "10.10.0.1"
set FN3.pubmqtt.port = "1883"

add pubchan-FN3 : LocalChannel
add subchan-FN3 : LocalChannel

bind FN3.FieldNode_0.sen_sen_readingJson_out pubchan-FN3

bind FN3.pubmqtt.jsonPub pubchan-FN3
bind FN3.submqtt.onTopicAndMsg subchan-FN3

//bind FN3.FieldNode_0.Fie_sen_reading_out chan
//bind FN3.FieldNode_0.Fie_sen_ready_out chan
//bind FN3.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN3.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN3.FieldNode_0.Fie_sen_read_in chan1


06:36:18 INFO WSGroup Broadcasting current model to 4 clients
```

**Comment by kehusa** [comment]
Still problems when trying to connect:

Log from Field Node:
```
06:48:30 ALL KevoreeLogger Set logLevel= info
06:48:34 INFO KevoreeCore Platform node name: FN1
06:48:39 ALL KevoreeLogger Set logLevel= info
06:48:39 INFO KevoreeCore Model deployed successfully: 6 adaptations (4808ms)
06:48:39 INFO WSGroup "sync" connected to master server ws://10.10.0.1:9000
06:49:10 INFO WSGroup Lost connection with master "node0" at ws://10.10.0.1:9000
Comparator ReadyFilter ReadyFilter ReadyDecoder ReadyMRAA Version: v0.6.1-10-gf33880c
```

Log from HomeGW(master):
```
06:47:20 INFO WSGroup New client registered "FN1"
06:47:27 DEBUG WSGroup Node's "FN1" model has been merged with the current one
06:47:27 DEBUG WSGroup onConnect KevScript to process:

add FN1.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN1.FieldNode_0.Properties_nodeName__var = "FN1"

add FN1.submqtt : MQTTSubClient/2.0.1
set FN1.submqtt.topic = "meg/smarttracker"
set FN1.submqtt.host = "10.10.0.1"
set FN1.submqtt.port = "1883"

add FN1.pubmqtt : MQTTPubClient/2.0.1
set FN1.pubmqtt.topic = "test/smarttracker"
set FN1.pubmqtt.host = "10.10.0.1"
set FN1.pubmqtt.port = "1883"

add pubchan-FN1 : LocalChannel
add subchan-FN1 : LocalChannel

bind FN1.FieldNode_0.sen_sen_readingJson_out pubchan-FN1

bind FN1.pubmqtt.jsonPub pubchan-FN1
bind FN1.submqtt.onTopicAndMsg subchan-FN1


06:47:33 INFO WSGroup Broadcasting current model to 1 client
06:47:33 DEBUG KevoreeCore Deploy process started...
06:47:39 INFO KevoreeCore Model deployed successfully: 0 adaptations (6274ms)
06:47:39 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
06:47:39 INFO MQTTSubClient comp846 closed connection with localhost:1883
06:47:39 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
06:47:39 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
06:47:40 INFO MQTTSubClient comp846 connected to localhost:1883
06:47:40 INFO MQTTSubClient comp846 subscribed to topic sensor/button
06:47:40 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
06:47:40 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
06:47:40 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
06:47:40 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:47:40 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
06:47:52 DEBUG WSGroup onDisconnect KevScript to process:

remove FN1

06:47:57 DEBUG KevoreeCore Deploy process started...
06:48:02 INFO KevoreeCore Model deployed successfully: 0 adaptations (4812ms)
06:48:02 INFO MQTTSubClient comp846 closed connection with localhost:1883
06:48:02 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
06:48:02 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
06:48:02 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
06:48:03 INFO MQTTSubClient comp846 connected to localhost:1883
06:48:03 INFO MQTTSubClient comp846 subscribed to topic sensor/button
06:48:03 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
06:48:03 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
06:48:03 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:48:03 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
06:48:03 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
06:48:39 INFO WSGroup New client registered "FN1"
06:48:48 DEBUG WSGroup Node's "FN1" model has been merged with the current one
06:48:48 DEBUG WSGroup onConnect KevScript to process:

add FN1.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN1.FieldNode_0.Properties_nodeName__var = "FN1"

add FN1.submqtt : MQTTSubClient/2.0.1
set FN1.submqtt.topic = "meg/smarttracker"
set FN1.submqtt.host = "10.10.0.1"
set FN1.submqtt.port = "1883"

add FN1.pubmqtt : MQTTPubClient/2.0.1
set FN1.pubmqtt.topic = "test/smarttracker"
set FN1.pubmqtt.host = "10.10.0.1"
set FN1.pubmqtt.port = "1883"

add pubchan-FN1 : LocalChannel
add subchan-FN1 : LocalChannel

bind FN1.FieldNode_0.sen_sen_readingJson_out pubchan-FN1

bind FN1.pubmqtt.jsonPub pubchan-FN1
bind FN1.submqtt.onTopicAndMsg subchan-FN1


06:48:54 INFO WSGroup Broadcasting current model to 1 client
06:48:54 DEBUG KevoreeCore Deploy process started...
06:49:00 INFO KevoreeCore Model deployed successfully: 0 adaptations (6764ms)
06:49:00 INFO MQTTSubClient comp846 closed connection with localhost:1883
06:49:01 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
06:49:01 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
06:49:01 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
06:49:02 INFO MQTTSubClient comp846 connected to localhost:1883
06:49:02 INFO MQTTSubClient comp846 subscribed to topic sensor/button
06:49:02 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
06:49:02 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
06:49:02 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
06:49:02 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
06:49:02 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
06:49:13 DEBUG WSGroup onDisconnect KevScript to process:

remove FN1

```

**Comment by kehusa** [comment]
```
Node ready: 3:[object Object]HomeGWLightController_lightSwitch (LightSwitch): ZWave?scanComplete()
09:28:13 INFO MQTTPubClient "pubmqtt" publishing "{"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]}" to "test/smarttracker/pressure"
09:28:13 INFO MQTTPubClient "pubmqtt" publishing "{"deviceId":"magnusuuiddevicen","observations":[{"lamp":"off"}]}" to "test/smarttracker/pressure"
09:28:40 INFO WSGroup Pull requested
09:29:37 INFO WSGroup New client registered "FN3"
09:29:42 DEBUG WSGroup Node's "FN3" model has been merged with the current one
09:29:42 DEBUG WSGroup onConnect KevScript to process:

add FN3.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN3.FieldNode_0.Properties_nodeName__var = "FN3"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN3.submqtt : MQTTSubClient/2.0.1
set FN3.submqtt.topic = "meg/smarttracker"
set FN3.submqtt.host = "10.10.0.1"
set FN3.submqtt.port = "1883"

add FN3.pubmqtt : MQTTPubClient/2.0.1
set FN3.pubmqtt.topic = "test/smarttracker"
set FN3.pubmqtt.host = "10.10.0.1"
set FN3.pubmqtt.port = "1883"

add pubchan-FN3 : LocalChannel
add subchan-FN3 : LocalChannel

bind FN3.FieldNode_0.sen_sen_readingJson_out pubchan-FN3

bind FN3.pubmqtt.jsonPub pubchan-FN3
bind FN3.submqtt.onTopicAndMsg subchan-FN3

//bind FN3.FieldNode_0.Fie_sen_reading_out chan
//bind FN3.FieldNode_0.Fie_sen_ready_out chan
//bind FN3.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN3.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN3.FieldNode_0.Fie_sen_read_in chan1


09:29:47 INFO WSGroup Broadcasting current model to 1 client
09:29:47 DEBUG KevoreeCore Deploy process started...
09:29:51 INFO KevoreeCore Model deployed successfully: 0 adaptations (4084ms)
09:31:02 INFO WSGroup New client registered "FN1"
09:31:07 DEBUG WSGroup Node's "FN1" model has been merged with the current one
09:31:07 DEBUG WSGroup onConnect KevScript to process:

add FN1.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN1.FieldNode_0.Properties_nodeName__var = "FN1"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN1.submqtt : MQTTSubClient/2.0.1
set FN1.submqtt.topic = "meg/smarttracker"
set FN1.submqtt.host = "10.10.0.1"
set FN1.submqtt.port = "1883"

add FN1.pubmqtt : MQTTPubClient/2.0.1
set FN1.pubmqtt.topic = "test/smarttracker"
set FN1.pubmqtt.host = "10.10.0.1"
set FN1.pubmqtt.port = "1883"

add pubchan-FN1 : LocalChannel
add subchan-FN1 : LocalChannel

bind FN1.FieldNode_0.sen_sen_readingJson_out pubchan-FN1

bind FN1.pubmqtt.jsonPub pubchan-FN1
bind FN1.submqtt.onTopicAndMsg subchan-FN1

//bind FN1.FieldNode_0.Fie_sen_reading_out chan
//bind FN1.FieldNode_0.Fie_sen_ready_out chan
//bind FN1.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN1.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN1.FieldNode_0.Fie_sen_read_in chan1


09:31:11 INFO WSGroup Broadcasting current model to 2 clients
09:31:11 DEBUG KevoreeCore Deploy process started...
09:31:16 INFO KevoreeCore Model deployed successfully: 0 adaptations (4810ms)
09:31:16 INFO MQTTSubClient comp846 closed connection with localhost:1883
09:31:16 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
09:31:16 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
09:31:16 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
09:31:17 INFO MQTTSubClient comp846 connected to localhost:1883
09:31:17 INFO MQTTSubClient comp846 subscribed to topic sensor/button
09:31:17 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
09:31:17 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
09:31:17 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
09:31:18 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
09:31:18 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
09:34:27 INFO WSGroup New client registered "FN4"
09:34:33 DEBUG WSGroup Node's "FN4" model has been merged with the current one
09:34:33 DEBUG WSGroup onConnect KevScript to process:

add FN4.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN4.FieldNode_0.Properties_nodeName__var = "FN4"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN4.submqtt : MQTTSubClient/2.0.1
set FN4.submqtt.topic = "meg/smarttracker"
set FN4.submqtt.host = "10.10.0.1"
set FN4.submqtt.port = "1883"

add FN4.pubmqtt : MQTTPubClient/2.0.1
set FN4.pubmqtt.topic = "test/smarttracker"
set FN4.pubmqtt.host = "10.10.0.1"
set FN4.pubmqtt.port = "1883"

add pubchan-FN4 : LocalChannel
add subchan-FN4 : LocalChannel

bind FN4.FieldNode_0.sen_sen_readingJson_out pubchan-FN4

bind FN4.pubmqtt.jsonPub pubchan-FN4
bind FN4.submqtt.onTopicAndMsg subchan-FN4

//bind FN4.FieldNode_0.Fie_sen_reading_out chan
//bind FN4.FieldNode_0.Fie_sen_ready_out chan
//bind FN4.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN4.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN4.FieldNode_0.Fie_sen_read_in chan1


09:34:39 INFO WSGroup Broadcasting current model to 3 clients
09:34:39 DEBUG KevoreeCore Deploy process started...
09:34:45 INFO KevoreeCore Model deployed successfully: 0 adaptations (5989ms)
09:34:45 INFO MQTTSubClient comp846 closed connection with localhost:1883
09:34:45 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
09:34:45 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
09:34:45 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
09:34:46 INFO MQTTSubClient comp846 connected to localhost:1883
09:34:46 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
09:34:46 INFO MQTTSubClient comp846 subscribed to topic sensor/button
09:34:46 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
09:34:46 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
09:34:46 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
09:34:46 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
09:35:45 DEBUG WSGroup onDisconnect KevScript to process:

remove FN4

09:35:48 INFO WSGroup Broadcasting current model to 3 clients
09:35:48 DEBUG KevoreeCore Deploy process started...
09:35:52 INFO KevoreeCore Model deployed successfully: 0 adaptations (4358ms)
09:35:52 INFO MQTTSubClient comp846 closed connection with localhost:1883
09:35:52 INFO MQTTSubClient fnsubmqtt closed connection with localhost:1883
09:35:52 INFO MQTTSubClient submqtt closed connection with ri.smarttracker.no:1883
09:35:52 INFO MQTTPubClient pubmqtt closed connection with ri.smarttracker.no:1883
09:35:52 INFO WSGroup New client registered "FN4"
09:35:58 DEBUG WSGroup Node's "FN4" model has been merged with the current one
09:35:58 DEBUG WSGroup onConnect KevScript to process:

add FN4.FieldNode_0 : no.tellu.FieldNode/1.0.28
set FN4.FieldNode_0.Properties_nodeName__var = "FN4"

//add chan: WSChan
//set chan.port = "9050"
//set chan.host = "10.10.0.1"

//add chan1: WSChan
//set chan1.port = "9050"
//set chan1.host = "10.10.0.1"

add FN4.submqtt : MQTTSubClient/2.0.1
set FN4.submqtt.topic = "meg/smarttracker"
set FN4.submqtt.host = "10.10.0.1"
set FN4.submqtt.port = "1883"

add FN4.pubmqtt : MQTTPubClient/2.0.1
set FN4.pubmqtt.topic = "test/smarttracker"
set FN4.pubmqtt.host = "10.10.0.1"
set FN4.pubmqtt.port = "1883"

add pubchan-FN4 : LocalChannel
add subchan-FN4 : LocalChannel

bind FN4.FieldNode_0.sen_sen_readingJson_out pubchan-FN4

bind FN4.pubmqtt.jsonPub pubchan-FN4
bind FN4.submqtt.onTopicAndMsg subchan-FN4

//bind FN4.FieldNode_0.Fie_sen_reading_out chan
//bind FN4.FieldNode_0.Fie_sen_ready_out chan
//bind FN4.FieldNode_0.Fie_sen_start_periodic_reading_in chan1
//bind FN4.FieldNode_0.Fie_sen_reading_cancel_in chan1
//bind FN4.FieldNode_0.Fie_sen_read_in chan1


09:36:03 INFO WSGroup Broadcasting current model to 3 clients
09:36:03 DEBUG KevoreeCore Deploy process started...
09:36:08 INFO KevoreeCore Model deployed successfully: 0 adaptations (5027ms)
09:36:08 INFO MQTTSubClient comp846 connected to localhost:1883
09:36:08 INFO MQTTSubClient fnsubmqtt connected to localhost:1883
09:36:08 INFO MQTTSubClient comp846 subscribed to topic sensor/button
09:36:08 INFO MQTTSubClient fnsubmqtt subscribed to topic sensor/fallIndex
09:36:08 INFO MQTTSubClient submqtt connected to ri.smarttracker.no:1883
09:36:08 INFO MQTTPubClient pubmqtt connected to ri.smarttracker.no:1883
09:36:08 INFO MQTTSubClient submqtt subscribed to topic meg/smarttracker
09:36:14 DEBUG WSGroup onDisconnect KevScript to process:

remove FN3

09:36:17 INFO WSGroup Broadcasting current model to 2 clients
09:36:17 DEBUG KevoreeCore Deploy process started...
09:36:22 INFO KevoreeCore Model deployed successfully: 0 adaptations (5067ms)
09:36:25 DEBUG WSGroup onDisconnect KevScript to process:

remove FN4

09:36:28 INFO WSGroup Broadcasting current model to 3 clients
09:36:28 DEBUG KevoreeCore Deploy process started...
09:36:32 INFO KevoreeCore Model deployed successfully: 0 adaptations (4400ms)
09:36:34 DEBUG WSGroup onDisconnect KevScript to process:

remove FN1

09:36:37 INFO WSGroup Broadcasting current model to 1 client
09:36:37 DEBUG KevoreeCore Deploy process started...
09:36:41 INFO KevoreeCore Model deployed successfully: 0 adaptations (4301ms)
events.js:85
throw er; // Unhandled 'error' event
^
Error: zlib binding closed
at DeflateRaw.Zlib._transform (zlib.js:487:15)
at DeflateRaw.Transform._read (_stream_transform.js:179:10)
at DeflateRaw.Transform._write (_stream_transform.js:167:12)
at doWrite (_stream_writable.js:301:12)
at writeOrBuffer (_stream_writable.js:288:5)
at DeflateRaw.Writable.write (_stream_writable.js:217:11)
at DeflateRaw.Zlib.flush (zlib.js:456:10)
at DeflateRaw.<anonymous> (zlib.js:452:12)
at DeflateRaw.g (events.js:199:16)
at DeflateRaw.emit (events.js:104:17)

```

**Comment by kehusa** [comment]
I think this can be closed. It was partly caused my a misconfiguration and a too short timeout
